import Head from 'next/head'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import avatar from "../public/3d-avatar.png";
import code from "../public/code.png";
import design from "../public/design.png";
import mentoring from "../public/mentor.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Reef Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen  mb-20">
          <nav className="py-8 mb-1 flex justify-between dark:text-white">
            <h1 className="font-poppins text-xl">REEF | A Simple React Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(prev => !prev)}
                className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex flex-col justify-center justify-items-center text-center p-10 py-0">
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full relative overflow-hidden md:h-80 md:w-80 w-44 h-44">
              <Image src={avatar} layout="fill" objectFit="cover" alt="avatar"/>
            </div>
            <h2 className="text-5xl py-5 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Farid Vatani
            </h2>
            <h3 className="text-2xl py-0 dark:text-white md:text-3xl">
              Front End Engineer
            </h3>
            <p className="text-md py-5 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I work with the JavaScript ecosystem. Welcome to my small piece of the internet,
              where I write and share about different topics related to the tech industry and life style.
            </p>
            <div className="text-5xl flex justify-center gap-10 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </div>
        </section>

        <section>
          <div>
          <h3 className="text-4xl py-2 dark:text-white uppercase">Services</h3>
          <div className="border-solid border-2 border-teal-400"></div>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I address all design and technical challenges, identify any risk areas, 
            and create a sound foundation for your product based on budget, timeline, and technology. I deliver your product blueprint, complete with the app&apos;s architecture.
            As a product development company, I help businesses ideate, strategize, iterate,
            and launch their mobile and web apps while keeping cost, timelines, and objectives in mind.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-transparent border-solid border-2 border-teal-400  flex-1">
              <Image src={design} width={100} height={100} alt="image-1" />
              <h3 className="text-lg dark:text-white font-medium pt-8 pb-2">Designer</h3>
              <p className="dark:text-white py-2">
                I value simple content structure, clean design patterns, and thoughtful interactions.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-transparent border-solid border-2 border-teal-400  flex-1">
              <Image src={code} width={100} height={100} alt="image-2"/>
              <h3 className="text-lg dark:text-white font-medium pt-8 pb-2">Frontend Developer</h3>
              <p className="dark:text-white py-2">
                I like to code things from scratch, and enjoy bringing ideas to life in the browser.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-transparent border-solid border-2 border-teal-400 flex-1">
              <Image src={mentoring} width={100} height={100} alt="image-3"/>
              <h3 className="text-lg dark:text-white font-medium pt-8 pb-2 ">Mentor</h3>
              <p className="dark:text-white py-2">
                I genuinely care about people, and love helping fellow designers work on their craft.
              </p>
            </div>
          </div>
        </section>
        
        <section className="py-10">
          <div>
            <h3 className="text-4xl py-2 dark:text-white uppercase">Portfolios</h3>
            <div className="border-solid border-2 border-teal-400"></div>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Whether your app needs to be built using <span className="text-teal-500">Node.js, React.js, Typescript</span>, or some other programming language, 
              I hit sprint deadlines on time and according to your technical requirements. I focus on building scalable apps that facilitate incremental improvements to your product.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="Portfolio-1"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="Portfolio-2"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="Portfolio-3"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="Portfolio-4"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="Portfolio-5"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="Portfolio-6"
              />
            </div>
          </div>
        </section>

      </main>
      <footer className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 dark:text-white text-center p-6 border-solid border-b-8 border-teal-500">
        <span>© 2022 Copyright | Made With ❤️ By </span>
        <a className="text-cyan-600 font-poppins" href="https://faridvatani.ir/">Farid Vatani</a>
      </footer>
    </div>
  )
}
